name: streetanimals
description: This app is created for the google play and app academy Bootcamp 2023.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  rive: ^0.11.3
  google_sign_in: ^6.1.4
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/fonts/
    - assets/rive/

  fonts:
    - family: Montserrat-Black
      fonts:
        - asset: assets\fonts\Montserrat-Black.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets\fonts\Montserrat-Bold.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets\fonts\Montserrat-Light.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets\fonts\Montserrat-Regular.ttf
